import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { AdminReportPayload } from "@/lib/admin-report";

function fmtMoney(n: number): string {
  return n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export function generateAdminReportPdf(payload: AdminReportPayload): Buffer {
  const doc = new jsPDF({ orientation: "p", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 14;
  let y = 18;

  const drawFooter = (pageNumber: number, pageCount: number) => {
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text(
      `Page ${pageNumber} of ${pageCount}`,
      pageW / 2,
      pageH - 8,
      { align: "center" }
    );
    doc.setTextColor(0);
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Admin Dashboard Report", pageW / 2, y, { align: "center" });
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(80);
  doc.text(`Generated: ${new Date(payload.generatedAt).toLocaleString("en-US")}`, margin, y);
  y += 5;
  doc.text(`Period: ${payload.periodLabel}`, margin, y);
  y += 5;
  doc.text("Generated by: Admin", margin, y);
  y += 5;
  doc.text("Data source: Google Sheet (requests)", margin, y);
  doc.setTextColor(0);
  y += 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("1. Summary", margin, y);
  y += 6;
  doc.setFont("helvetica", "normal");

  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value"]],
    body: [
      ["Total orders", String(payload.summary.totalOrders)],
      ["Total custom orders", String(payload.summary.totalCustomOrders)],
      ["Total customers", String(payload.summary.totalCustomers)],
      ["Total revenue (orders + custom)", fmtMoney(payload.summary.totalRevenue)],
    ],
    styles: { fontSize: 9, cellPadding: 3, lineColor: [200, 200, 200], lineWidth: 0.1 },
    headStyles: { fillColor: [30, 64, 175], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { left: margin, right: margin },
    tableLineColor: [200, 200, 200],
    tableLineWidth: 0.1,
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;

  const emptyRow = (cols: number, label: string) => [
    label,
    ...Array(Math.max(0, cols - 1)).fill("—"),
  ];

  const section = (title: string, head: string[][], body: (string | number)[][]) => {
    if (y > pageH - 40) {
      doc.addPage();
      y = margin;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(title, margin, y);
    y += 5;
    doc.setFont("helvetica", "normal");

    const cols = head[0]?.length ?? 1;
    const tableBody =
      body.length > 0 ? body : [emptyRow(cols, "No records in this section")];

    autoTable(doc, {
      startY: y,
      head,
      body: tableBody,
      styles: { fontSize: 8, cellPadding: 2, lineColor: [200, 200, 200], lineWidth: 0.1 },
      headStyles: { fillColor: [30, 64, 175], textColor: 255, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [243, 244, 246] },
      margin: { left: margin, right: margin },
      tableLineColor: [200, 200, 200],
      tableLineWidth: 0.1,
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  };

  section(
    "2. Orders",
    [["Order ID", "Customer", "Total", "Status", "Date"]],
    payload.orders.map((o) => [o.orderId, o.customer, fmtMoney(o.total), o.status, o.date])
  );

  section(
    "3. Custom orders",
    [["Order ID", "Customer", "Service", "Price", "Status", "Date"]],
    payload.customOrders.map((o) => [
      o.orderId,
      o.customer,
      o.service,
      fmtMoney(o.price),
      o.status,
      o.date,
    ])
  );

  section(
    "4. Customers",
    [["Customer name", "Email", "Phone", "Total orders"]],
    payload.customers.map((c) => [c.name, c.email, c.phone, String(c.totalOrders)])
  );

  section(
    "5. Payments",
    [["Payment ID", "Customer", "Amount", "Method", "Status", "Date"]],
    payload.payments.map((p) => [
      p.paymentId,
      p.customer,
      fmtMoney(p.amount),
      p.method,
      p.status,
      p.date,
    ])
  );

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    drawFooter(i, pageCount);
  }

  return Buffer.from(doc.output("arraybuffer"));
}
