<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Admin Dashboard Report</title>
    <style>
        @page {
            margin: 22mm 16mm 26mm 16mm;
        }
        * {
            box-sizing: border-box;
        }
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 9pt;
            color: #111827;
            line-height: 1.35;
            margin: 0;
        }
        .header {
            border-bottom: 2px solid #1e40af;
            padding-bottom: 12px;
            margin-bottom: 16px;
        }
        .header-row {
            width: 100%;
        }
        .header-row td {
            vertical-align: top;
        }
        .logo {
            max-height: 48px;
            max-width: 160px;
        }
        .title {
            font-size: 18pt;
            font-weight: bold;
            color: #1e3a8a;
            margin: 0 0 4px 0;
        }
        .meta {
            font-size: 8.5pt;
            color: #4b5563;
        }
        .meta strong {
            color: #374151;
        }
        h2 {
            font-size: 11pt;
            color: #1e40af;
            margin: 18px 0 8px 0;
            padding-bottom: 4px;
            border-bottom: 1px solid #e5e7eb;
        }
        .summary {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 8px;
        }
        .summary td {
            width: 20%;
            padding: 10px 8px;
            border: 1px solid #d1d5db;
            background: #f9fafb;
            text-align: center;
            vertical-align: middle;
        }
        .summary .label {
            display: block;
            font-size: 7.5pt;
            color: #6b7280;
            text-transform: uppercase;
            letter-spacing: 0.02em;
            margin-bottom: 4px;
        }
        .summary .value {
            font-size: 12pt;
            font-weight: bold;
            color: #111827;
        }
        table.data {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 6px;
            font-size: 8pt;
        }
        table.data thead th {
            background: #1e40af;
            color: #ffffff;
            font-weight: bold;
            padding: 7px 5px;
            text-align: left;
            border: 1px solid #1e3a8a;
        }
        table.data tbody td {
            padding: 6px 5px;
            border: 1px solid #e5e7eb;
            vertical-align: top;
        }
        table.data tbody tr:nth-child(even) {
            background: #f3f4f6;
        }
        table.data tbody tr:nth-child(odd) {
            background: #ffffff;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .totals-box {
            margin-top: 20px;
            padding: 12px 14px;
            background: #eff6ff;
            border: 1px solid #bfdbfe;
            border-radius: 4px;
        }
        .totals-box table {
            width: 100%;
            font-size: 9pt;
        }
        .totals-box td {
            padding: 4px 0;
        }
        .totals-box .grand {
            font-weight: bold;
            font-size: 10pt;
            color: #1e3a8a;
            border-top: 1px solid #93c5fd;
            padding-top: 8px;
        }
        .footer-note {
            margin-top: 14px;
            font-size: 7.5pt;
            color: #9ca3af;
            text-align: center;
        }
    </style>
</head>
<body>

<div class="header">
    <table class="header-row" cellpadding="0" cellspacing="0">
        <tr>
            <td style="width: 30%;">
                @if(!empty($logoBase64))
                    <img class="logo" src="data:image/png;base64,{{ $logoBase64 }}" alt="Logo">
                @endif
            </td>
            <td style="width: 70%; text-align: right;">
                <p class="title">Admin Dashboard Report</p>
                <p class="meta">
                    <strong>Generated:</strong> {{ $generatedAt->timezone(config('app.timezone'))->format('M j, Y \a\t g:i A') }}<br>
                    <strong>Generated by:</strong> {{ $generatedBy }}<br>
                    @if($hasPeriod)
                        <strong>Report period:</strong>
                        {{ $periodStart->format('M j, Y') }} — {{ $periodEnd->format('M j, Y') }}
                    @else
                        <strong>Report period:</strong> All time
                    @endif
                </p>
            </td>
        </tr>
    </table>
</div>

<h2>Summary</h2>
<table class="summary" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <span class="label">Total orders</span>
            <span class="value">{{ number_format($summary['total_orders']) }}</span>
        </td>
        <td>
            <span class="label">Custom orders</span>
            <span class="value">{{ number_format($summary['total_custom_orders']) }}</span>
        </td>
        <td>
            <span class="label">Customers</span>
            <span class="value">{{ number_format($summary['total_customers']) }}</span>
        </td>
        <td>
            <span class="label">Total revenue</span>
            <span class="value">{{ number_format($summary['total_revenue'], 2) }}</span>
        </td>
        <td>
            <span class="label">Pending orders</span>
            <span class="value">{{ number_format($summary['pending_orders']) }}</span>
        </td>
    </tr>
</table>

<h2>Orders</h2>
<table class="data">
    <thead>
    <tr>
        <th>Order ID</th>
        <th>Customer</th>
        <th>Product</th>
        <th class="text-center">Qty</th>
        <th class="text-right">Total</th>
        <th>Status</th>
        <th>Order date</th>
    </tr>
    </thead>
    <tbody>
    @forelse($orders as $order)
        <tr>
            <td>#{{ $order->id }}</td>
            <td>{{ $order->customer?->name ?? '—' }}</td>
            <td>{{ $order->product }}</td>
            <td class="text-center">{{ $order->quantity }}</td>
            <td class="text-right">{{ number_format((float) $order->total_price, 2) }}</td>
            <td>{{ ucfirst($order->status) }}</td>
            <td>{{ $order->order_date?->format('M j, Y') }}</td>
        </tr>
    @empty
        <tr>
            <td colspan="7" class="text-center">No orders in this period.</td>
        </tr>
    @endforelse
    </tbody>
</table>

<h2>Custom orders</h2>
<table class="data">
    <thead>
    <tr>
        <th>Order ID</th>
        <th>Customer</th>
        <th>Service type</th>
        <th class="text-right">Price</th>
        <th>Status</th>
        <th>Created</th>
    </tr>
    </thead>
    <tbody>
    @forelse($customOrders as $co)
        <tr>
            <td>#{{ $co->id }}</td>
            <td>{{ $co->customer?->name ?? '—' }}</td>
            <td>{{ $co->service_type }}</td>
            <td class="text-right">{{ number_format((float) $co->price, 2) }}</td>
            <td>{{ ucfirst($co->status) }}</td>
            <td>{{ $co->created_at?->format('M j, Y') }}</td>
        </tr>
    @empty
        <tr>
            <td colspan="6" class="text-center">No custom orders in this period.</td>
        </tr>
    @endforelse
    </tbody>
</table>

<h2>Customers</h2>
<table class="data">
    <thead>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th class="text-center">Total orders</th>
        <th class="text-right">Total spent</th>
    </tr>
    </thead>
    <tbody>
    @forelse($customers as $customer)
        @php
            $spent = (float) ($customer->orders_sum_total_price ?? 0) + (float) ($customer->custom_orders_sum_price ?? 0);
        @endphp
        <tr>
            <td>{{ $customer->name }}</td>
            <td>{{ $customer->email ?? '—' }}</td>
            <td>{{ $customer->phone ?? '—' }}</td>
            <td class="text-center">{{ number_format($customer->orders_count) }}</td>
            <td class="text-right">{{ number_format($spent, 2) }}</td>
        </tr>
    @empty
        <tr>
            <td colspan="5" class="text-center">No customers match this report.</td>
        </tr>
    @endforelse
    </tbody>
</table>

<h2>Payments</h2>
<table class="data">
    <thead>
    <tr>
        <th>Payment ID</th>
        <th>Customer</th>
        <th class="text-right">Amount</th>
        <th>Method</th>
        <th>Status</th>
        <th>Payment date</th>
    </tr>
    </thead>
    <tbody>
    @forelse($payments as $payment)
        <tr>
            <td>#{{ $payment->id }}</td>
            <td>{{ $payment->customer?->name ?? '—' }}</td>
            <td class="text-right">{{ number_format((float) $payment->amount, 2) }}</td>
            <td>{{ $payment->payment_method }}</td>
            <td>{{ ucfirst($payment->status) }}</td>
            <td>{{ $payment->payment_date?->format('M j, Y') }}</td>
        </tr>
    @empty
        <tr>
            <td colspan="6" class="text-center">No payments in this period.</td>
        </tr>
    @endforelse
    </tbody>
</table>

<div class="totals-box">
    <table cellpadding="0" cellspacing="0">
        <tr>
            <td>Orders revenue ({{ number_format($totals['order_count']) }} orders)</td>
            <td class="text-right">{{ number_format($totals['orders_revenue'], 2) }}</td>
        </tr>
        <tr>
            <td>Custom orders revenue ({{ number_format($totals['custom_order_count']) }} orders)</td>
            <td class="text-right">{{ number_format($totals['custom_orders_revenue'], 2) }}</td>
        </tr>
        <tr>
            <td class="grand">Combined revenue</td>
            <td class="text-right grand">{{ number_format($totals['combined_revenue'], 2) }}</td>
        </tr>
    </table>
</div>

<p class="footer-note">Confidential — for internal use only.</p>

<script type="text/php">
if (isset($pdf)) {
    $font = $fontMetrics->get_font("DejaVu Sans", "normal");
    $size = 8;
    $color = array(0.45, 0.45, 0.45);
    $pdf->page_text(480, 805, "Page {PAGE_NUM} of {PAGE_COUNT}", $font, $size, $color);
}
</script>

</body>
</html>
